### ISSUE TITLE
Is this compatible with Blazor Client WASM apps?

### ISSUE THREAD

**Issue by bryanp-ramosoil** [georgemathieson/blazor-markdown#4]
I found your project and wanted to try it out. I'm using client side Blazor and when using client side your app is unable to find the file. 

https://localhost:44315/Markdown/LeaseFunctionHelp.md (Found when using the browser) 

<Markdown FilePath="Markdown/LeaseFunctionHelp.md" />

Thanks!!

**Comment by georgemathieson** [comment]
Not currently supported I’m afraid.
